// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\FIRoldVersion\coeffs_registers.v
// Created: 2025-05-05 17:40:17
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: coeffs_registers
// Source Path: FIRoldVersion/Programmable FIR via Registers/coeffs_registers
// Hierarchy Level: 1
// Model version: 8.0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module coeffs_registers
          (clk,
           reset,
           enb,
           coeffs_in,
           write_address,
           write_enable,
           coeffs_out_0,
           coeffs_out_1,
           coeffs_out_2,
           coeffs_out_3,
           coeffs_out_4,
           coeffs_out_5,
           coeffs_out_6,
           coeffs_out_7,
           coeffs_out_8,
           coeffs_out_9,
           coeffs_out_10,
           coeffs_out_11,
           coeffs_out_12,
           coeffs_out_13,
           coeffs_out_14,
           coeffs_out_15,
           coeffs_out_16,
           coeffs_out_17,
           coeffs_out_18,
           coeffs_out_19,
           coeffs_out_20,
           coeffs_out_21,
           coeffs_out_22,
           coeffs_out_23,
           coeffs_out_24,
           coeffs_out_25,
           coeffs_out_26,
           coeffs_out_27,
           coeffs_out_28,
           coeffs_out_29,
           coeffs_out_30,
           coeffs_out_31,
           coeffs_out_32,
           coeffs_out_33,
           coeffs_out_34,
           coeffs_out_35,
           coeffs_out_36,
           coeffs_out_37,
           coeffs_out_38,
           coeffs_out_39,
           coeffs_out_40,
           coeffs_out_41,
           coeffs_out_42);


  input   clk;
  input   reset;
  input   enb;
  input   signed [13:0] coeffs_in;  // sfix14_En13
  input   [7:0] write_address;  // uint8
  input   write_enable;
  output  signed [13:0] coeffs_out_0;  // sfix14_En13
  output  signed [13:0] coeffs_out_1;  // sfix14_En13
  output  signed [13:0] coeffs_out_2;  // sfix14_En13
  output  signed [13:0] coeffs_out_3;  // sfix14_En13
  output  signed [13:0] coeffs_out_4;  // sfix14_En13
  output  signed [13:0] coeffs_out_5;  // sfix14_En13
  output  signed [13:0] coeffs_out_6;  // sfix14_En13
  output  signed [13:0] coeffs_out_7;  // sfix14_En13
  output  signed [13:0] coeffs_out_8;  // sfix14_En13
  output  signed [13:0] coeffs_out_9;  // sfix14_En13
  output  signed [13:0] coeffs_out_10;  // sfix14_En13
  output  signed [13:0] coeffs_out_11;  // sfix14_En13
  output  signed [13:0] coeffs_out_12;  // sfix14_En13
  output  signed [13:0] coeffs_out_13;  // sfix14_En13
  output  signed [13:0] coeffs_out_14;  // sfix14_En13
  output  signed [13:0] coeffs_out_15;  // sfix14_En13
  output  signed [13:0] coeffs_out_16;  // sfix14_En13
  output  signed [13:0] coeffs_out_17;  // sfix14_En13
  output  signed [13:0] coeffs_out_18;  // sfix14_En13
  output  signed [13:0] coeffs_out_19;  // sfix14_En13
  output  signed [13:0] coeffs_out_20;  // sfix14_En13
  output  signed [13:0] coeffs_out_21;  // sfix14_En13
  output  signed [13:0] coeffs_out_22;  // sfix14_En13
  output  signed [13:0] coeffs_out_23;  // sfix14_En13
  output  signed [13:0] coeffs_out_24;  // sfix14_En13
  output  signed [13:0] coeffs_out_25;  // sfix14_En13
  output  signed [13:0] coeffs_out_26;  // sfix14_En13
  output  signed [13:0] coeffs_out_27;  // sfix14_En13
  output  signed [13:0] coeffs_out_28;  // sfix14_En13
  output  signed [13:0] coeffs_out_29;  // sfix14_En13
  output  signed [13:0] coeffs_out_30;  // sfix14_En13
  output  signed [13:0] coeffs_out_31;  // sfix14_En13
  output  signed [13:0] coeffs_out_32;  // sfix14_En13
  output  signed [13:0] coeffs_out_33;  // sfix14_En13
  output  signed [13:0] coeffs_out_34;  // sfix14_En13
  output  signed [13:0] coeffs_out_35;  // sfix14_En13
  output  signed [13:0] coeffs_out_36;  // sfix14_En13
  output  signed [13:0] coeffs_out_37;  // sfix14_En13
  output  signed [13:0] coeffs_out_38;  // sfix14_En13
  output  signed [13:0] coeffs_out_39;  // sfix14_En13
  output  signed [13:0] coeffs_out_40;  // sfix14_En13
  output  signed [13:0] coeffs_out_41;  // sfix14_En13
  output  signed [13:0] coeffs_out_42;  // sfix14_En13


  reg signed [13:0] coeffs_regs [0:42];  // sfix14_En13 [43]
  reg signed [13:0] coeffs_assigned [0:42];  // sfix14_En13 [43]
  reg signed [31:0] coeffs_assignment_i;  // int32
  reg [7:0] coeffs_assignment_t_0_0 [0:42];  // ufix8 [43]
  reg signed [31:0] coeffs_regs_t_0_0;  // int32
  reg signed [31:0] coeffs_regs_t_1;  // int32


  always @* begin

    for(coeffs_assignment_i = 32'sd0; coeffs_assignment_i <= 32'sd42; coeffs_assignment_i = coeffs_assignment_i + 32'sd1) begin
      coeffs_assignment_t_0_0[coeffs_assignment_i] = coeffs_assignment_i[7:0];
      if (write_address == coeffs_assignment_t_0_0[coeffs_assignment_i]) begin
        coeffs_assigned[coeffs_assignment_i] = coeffs_in;
      end
      else begin
        coeffs_assigned[coeffs_assignment_i] = coeffs_regs[coeffs_assignment_i];
      end
    end

  end


  always @(posedge clk or posedge reset)
    begin : coeffs_regs_1_process
      if (reset == 1'b1) begin
        for(coeffs_regs_t_1 = 32'sd0; coeffs_regs_t_1 <= 32'sd42; coeffs_regs_t_1 = coeffs_regs_t_1 + 32'sd1) begin
          coeffs_regs[coeffs_regs_t_1] <= 14'sb00000000000000;
        end
      end
      else begin
        if (enb && write_enable) begin
          for(coeffs_regs_t_0_0 = 32'sd0; coeffs_regs_t_0_0 <= 32'sd42; coeffs_regs_t_0_0 = coeffs_regs_t_0_0 + 32'sd1) begin
            coeffs_regs[coeffs_regs_t_0_0] <= coeffs_assigned[coeffs_regs_t_0_0];
          end
        end
      end
    end


  assign coeffs_out_0 = coeffs_regs[0];

  assign coeffs_out_1 = coeffs_regs[1];

  assign coeffs_out_2 = coeffs_regs[2];

  assign coeffs_out_3 = coeffs_regs[3];

  assign coeffs_out_4 = coeffs_regs[4];

  assign coeffs_out_5 = coeffs_regs[5];

  assign coeffs_out_6 = coeffs_regs[6];

  assign coeffs_out_7 = coeffs_regs[7];

  assign coeffs_out_8 = coeffs_regs[8];

  assign coeffs_out_9 = coeffs_regs[9];

  assign coeffs_out_10 = coeffs_regs[10];

  assign coeffs_out_11 = coeffs_regs[11];

  assign coeffs_out_12 = coeffs_regs[12];

  assign coeffs_out_13 = coeffs_regs[13];

  assign coeffs_out_14 = coeffs_regs[14];

  assign coeffs_out_15 = coeffs_regs[15];

  assign coeffs_out_16 = coeffs_regs[16];

  assign coeffs_out_17 = coeffs_regs[17];

  assign coeffs_out_18 = coeffs_regs[18];

  assign coeffs_out_19 = coeffs_regs[19];

  assign coeffs_out_20 = coeffs_regs[20];

  assign coeffs_out_21 = coeffs_regs[21];

  assign coeffs_out_22 = coeffs_regs[22];

  assign coeffs_out_23 = coeffs_regs[23];

  assign coeffs_out_24 = coeffs_regs[24];

  assign coeffs_out_25 = coeffs_regs[25];

  assign coeffs_out_26 = coeffs_regs[26];

  assign coeffs_out_27 = coeffs_regs[27];

  assign coeffs_out_28 = coeffs_regs[28];

  assign coeffs_out_29 = coeffs_regs[29];

  assign coeffs_out_30 = coeffs_regs[30];

  assign coeffs_out_31 = coeffs_regs[31];

  assign coeffs_out_32 = coeffs_regs[32];

  assign coeffs_out_33 = coeffs_regs[33];

  assign coeffs_out_34 = coeffs_regs[34];

  assign coeffs_out_35 = coeffs_regs[35];

  assign coeffs_out_36 = coeffs_regs[36];

  assign coeffs_out_37 = coeffs_regs[37];

  assign coeffs_out_38 = coeffs_regs[38];

  assign coeffs_out_39 = coeffs_regs[39];

  assign coeffs_out_40 = coeffs_regs[40];

  assign coeffs_out_41 = coeffs_regs[41];

  assign coeffs_out_42 = coeffs_regs[42];

endmodule  // coeffs_registers

