// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\FIRoldVersion\Programmable_FIR_via_Registers.v
// Created: 2025-05-05 17:40:17
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1
// Target subsystem base rate: 1
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        1
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// filter_out                    ce_out        1
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Programmable_FIR_via_Registers
// Source Path: FIRoldVersion/Programmable FIR via Registers
// Hierarchy Level: 0
// Model version: 8.0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Programmable_FIR_via_Registers
          (clk,
           reset,
           clk_enable,
           coeffs_in,
           write_address,
           write_enable,
           write_done,
           filter_in,
           ce_out,
           filter_out);


  input   clk;
  input   reset;
  input   clk_enable;
  input   signed [13:0] coeffs_in;  // sfix14_En13
  input   [7:0] write_address;  // uint8
  input   write_enable;
  input   write_done;
  input   signed [13:0] filter_in;  // sfix14_En13
  output  ce_out;
  output  signed [14:0] filter_out;  // sfix15_En13


  wire enb;
  wire signed [13:0] coeffs_registers_out1_0;  // sfix14_En13
  wire signed [13:0] coeffs_registers_out1_1;  // sfix14_En13
  wire signed [13:0] coeffs_registers_out1_2;  // sfix14_En13
  wire signed [13:0] coeffs_registers_out1_3;  // sfix14_En13
  wire signed [13:0] coeffs_registers_out1_4;  // sfix14_En13
  wire signed [13:0] coeffs_registers_out1_5;  // sfix14_En13
  wire signed [13:0] coeffs_registers_out1_6;  // sfix14_En13
  wire signed [13:0] coeffs_registers_out1_7;  // sfix14_En13
  wire signed [13:0] coeffs_registers_out1_8;  // sfix14_En13
  wire signed [13:0] coeffs_registers_out1_9;  // sfix14_En13
  wire signed [13:0] coeffs_registers_out1_10;  // sfix14_En13
  wire signed [13:0] coeffs_registers_out1_11;  // sfix14_En13
  wire signed [13:0] coeffs_registers_out1_12;  // sfix14_En13
  wire signed [13:0] coeffs_registers_out1_13;  // sfix14_En13
  wire signed [13:0] coeffs_registers_out1_14;  // sfix14_En13
  wire signed [13:0] coeffs_registers_out1_15;  // sfix14_En13
  wire signed [13:0] coeffs_registers_out1_16;  // sfix14_En13
  wire signed [13:0] coeffs_registers_out1_17;  // sfix14_En13
  wire signed [13:0] coeffs_registers_out1_18;  // sfix14_En13
  wire signed [13:0] coeffs_registers_out1_19;  // sfix14_En13
  wire signed [13:0] coeffs_registers_out1_20;  // sfix14_En13
  wire signed [13:0] coeffs_registers_out1_21;  // sfix14_En13
  wire signed [13:0] coeffs_registers_out1_22;  // sfix14_En13
  wire signed [13:0] coeffs_registers_out1_23;  // sfix14_En13
  wire signed [13:0] coeffs_registers_out1_24;  // sfix14_En13
  wire signed [13:0] coeffs_registers_out1_25;  // sfix14_En13
  wire signed [13:0] coeffs_registers_out1_26;  // sfix14_En13
  wire signed [13:0] coeffs_registers_out1_27;  // sfix14_En13
  wire signed [13:0] coeffs_registers_out1_28;  // sfix14_En13
  wire signed [13:0] coeffs_registers_out1_29;  // sfix14_En13
  wire signed [13:0] coeffs_registers_out1_30;  // sfix14_En13
  wire signed [13:0] coeffs_registers_out1_31;  // sfix14_En13
  wire signed [13:0] coeffs_registers_out1_32;  // sfix14_En13
  wire signed [13:0] coeffs_registers_out1_33;  // sfix14_En13
  wire signed [13:0] coeffs_registers_out1_34;  // sfix14_En13
  wire signed [13:0] coeffs_registers_out1_35;  // sfix14_En13
  wire signed [13:0] coeffs_registers_out1_36;  // sfix14_En13
  wire signed [13:0] coeffs_registers_out1_37;  // sfix14_En13
  wire signed [13:0] coeffs_registers_out1_38;  // sfix14_En13
  wire signed [13:0] coeffs_registers_out1_39;  // sfix14_En13
  wire signed [13:0] coeffs_registers_out1_40;  // sfix14_En13
  wire signed [13:0] coeffs_registers_out1_41;  // sfix14_En13
  wire signed [13:0] coeffs_registers_out1_42;  // sfix14_En13
  wire signed [13:0] coeffs_registers_out1 [0:42];  // sfix14_En13 [43]
  reg signed [13:0] coeffs_shadow [0:42];  // sfix14_En13 [43]
  wire signed [14:0] Filter_Out_1;  // sfix15_En13
  reg signed [31:0] shadow_regs_t_0_0;  // int32
  reg signed [31:0] shadow_regs_t_1;  // int32


  coeffs_registers u_coeffs_registers (.clk(clk),
                                       .reset(reset),
                                       .enb(clk_enable),
                                       .coeffs_in(coeffs_in),  // sfix14_En13
                                       .write_address(write_address),  // uint8
                                       .write_enable(write_enable),
                                       .coeffs_out_0(coeffs_registers_out1_0),  // sfix14_En13
                                       .coeffs_out_1(coeffs_registers_out1_1),  // sfix14_En13
                                       .coeffs_out_2(coeffs_registers_out1_2),  // sfix14_En13
                                       .coeffs_out_3(coeffs_registers_out1_3),  // sfix14_En13
                                       .coeffs_out_4(coeffs_registers_out1_4),  // sfix14_En13
                                       .coeffs_out_5(coeffs_registers_out1_5),  // sfix14_En13
                                       .coeffs_out_6(coeffs_registers_out1_6),  // sfix14_En13
                                       .coeffs_out_7(coeffs_registers_out1_7),  // sfix14_En13
                                       .coeffs_out_8(coeffs_registers_out1_8),  // sfix14_En13
                                       .coeffs_out_9(coeffs_registers_out1_9),  // sfix14_En13
                                       .coeffs_out_10(coeffs_registers_out1_10),  // sfix14_En13
                                       .coeffs_out_11(coeffs_registers_out1_11),  // sfix14_En13
                                       .coeffs_out_12(coeffs_registers_out1_12),  // sfix14_En13
                                       .coeffs_out_13(coeffs_registers_out1_13),  // sfix14_En13
                                       .coeffs_out_14(coeffs_registers_out1_14),  // sfix14_En13
                                       .coeffs_out_15(coeffs_registers_out1_15),  // sfix14_En13
                                       .coeffs_out_16(coeffs_registers_out1_16),  // sfix14_En13
                                       .coeffs_out_17(coeffs_registers_out1_17),  // sfix14_En13
                                       .coeffs_out_18(coeffs_registers_out1_18),  // sfix14_En13
                                       .coeffs_out_19(coeffs_registers_out1_19),  // sfix14_En13
                                       .coeffs_out_20(coeffs_registers_out1_20),  // sfix14_En13
                                       .coeffs_out_21(coeffs_registers_out1_21),  // sfix14_En13
                                       .coeffs_out_22(coeffs_registers_out1_22),  // sfix14_En13
                                       .coeffs_out_23(coeffs_registers_out1_23),  // sfix14_En13
                                       .coeffs_out_24(coeffs_registers_out1_24),  // sfix14_En13
                                       .coeffs_out_25(coeffs_registers_out1_25),  // sfix14_En13
                                       .coeffs_out_26(coeffs_registers_out1_26),  // sfix14_En13
                                       .coeffs_out_27(coeffs_registers_out1_27),  // sfix14_En13
                                       .coeffs_out_28(coeffs_registers_out1_28),  // sfix14_En13
                                       .coeffs_out_29(coeffs_registers_out1_29),  // sfix14_En13
                                       .coeffs_out_30(coeffs_registers_out1_30),  // sfix14_En13
                                       .coeffs_out_31(coeffs_registers_out1_31),  // sfix14_En13
                                       .coeffs_out_32(coeffs_registers_out1_32),  // sfix14_En13
                                       .coeffs_out_33(coeffs_registers_out1_33),  // sfix14_En13
                                       .coeffs_out_34(coeffs_registers_out1_34),  // sfix14_En13
                                       .coeffs_out_35(coeffs_registers_out1_35),  // sfix14_En13
                                       .coeffs_out_36(coeffs_registers_out1_36),  // sfix14_En13
                                       .coeffs_out_37(coeffs_registers_out1_37),  // sfix14_En13
                                       .coeffs_out_38(coeffs_registers_out1_38),  // sfix14_En13
                                       .coeffs_out_39(coeffs_registers_out1_39),  // sfix14_En13
                                       .coeffs_out_40(coeffs_registers_out1_40),  // sfix14_En13
                                       .coeffs_out_41(coeffs_registers_out1_41),  // sfix14_En13
                                       .coeffs_out_42(coeffs_registers_out1_42)  // sfix14_En13
                                       );
  assign coeffs_registers_out1[0] = coeffs_registers_out1_0;
  assign coeffs_registers_out1[1] = coeffs_registers_out1_1;
  assign coeffs_registers_out1[2] = coeffs_registers_out1_2;
  assign coeffs_registers_out1[3] = coeffs_registers_out1_3;
  assign coeffs_registers_out1[4] = coeffs_registers_out1_4;
  assign coeffs_registers_out1[5] = coeffs_registers_out1_5;
  assign coeffs_registers_out1[6] = coeffs_registers_out1_6;
  assign coeffs_registers_out1[7] = coeffs_registers_out1_7;
  assign coeffs_registers_out1[8] = coeffs_registers_out1_8;
  assign coeffs_registers_out1[9] = coeffs_registers_out1_9;
  assign coeffs_registers_out1[10] = coeffs_registers_out1_10;
  assign coeffs_registers_out1[11] = coeffs_registers_out1_11;
  assign coeffs_registers_out1[12] = coeffs_registers_out1_12;
  assign coeffs_registers_out1[13] = coeffs_registers_out1_13;
  assign coeffs_registers_out1[14] = coeffs_registers_out1_14;
  assign coeffs_registers_out1[15] = coeffs_registers_out1_15;
  assign coeffs_registers_out1[16] = coeffs_registers_out1_16;
  assign coeffs_registers_out1[17] = coeffs_registers_out1_17;
  assign coeffs_registers_out1[18] = coeffs_registers_out1_18;
  assign coeffs_registers_out1[19] = coeffs_registers_out1_19;
  assign coeffs_registers_out1[20] = coeffs_registers_out1_20;
  assign coeffs_registers_out1[21] = coeffs_registers_out1_21;
  assign coeffs_registers_out1[22] = coeffs_registers_out1_22;
  assign coeffs_registers_out1[23] = coeffs_registers_out1_23;
  assign coeffs_registers_out1[24] = coeffs_registers_out1_24;
  assign coeffs_registers_out1[25] = coeffs_registers_out1_25;
  assign coeffs_registers_out1[26] = coeffs_registers_out1_26;
  assign coeffs_registers_out1[27] = coeffs_registers_out1_27;
  assign coeffs_registers_out1[28] = coeffs_registers_out1_28;
  assign coeffs_registers_out1[29] = coeffs_registers_out1_29;
  assign coeffs_registers_out1[30] = coeffs_registers_out1_30;
  assign coeffs_registers_out1[31] = coeffs_registers_out1_31;
  assign coeffs_registers_out1[32] = coeffs_registers_out1_32;
  assign coeffs_registers_out1[33] = coeffs_registers_out1_33;
  assign coeffs_registers_out1[34] = coeffs_registers_out1_34;
  assign coeffs_registers_out1[35] = coeffs_registers_out1_35;
  assign coeffs_registers_out1[36] = coeffs_registers_out1_36;
  assign coeffs_registers_out1[37] = coeffs_registers_out1_37;
  assign coeffs_registers_out1[38] = coeffs_registers_out1_38;
  assign coeffs_registers_out1[39] = coeffs_registers_out1_39;
  assign coeffs_registers_out1[40] = coeffs_registers_out1_40;
  assign coeffs_registers_out1[41] = coeffs_registers_out1_41;
  assign coeffs_registers_out1[42] = coeffs_registers_out1_42;

  assign enb = clk_enable;

  always @(posedge clk or posedge reset)
    begin : shadow_regs_process
      if (reset == 1'b1) begin
        for(shadow_regs_t_1 = 32'sd0; shadow_regs_t_1 <= 32'sd42; shadow_regs_t_1 = shadow_regs_t_1 + 32'sd1) begin
          coeffs_shadow[shadow_regs_t_1] <= 14'sb00000000000000;
        end
      end
      else begin
        if (enb && write_done) begin
          for(shadow_regs_t_0_0 = 32'sd0; shadow_regs_t_0_0 <= 32'sd42; shadow_regs_t_0_0 = shadow_regs_t_0_0 + 32'sd1) begin
            coeffs_shadow[shadow_regs_t_0_0] <= coeffs_registers_out1[shadow_regs_t_0_0];
          end
        end
      end
    end


  Discrete_FIR_Filter u_Discrete_FIR_Filter (.clk(clk),
                                             .reset(reset),
                                             .enb(clk_enable),
                                             .Discrete_FIR_Filter_in(filter_in),  // sfix14_En13
                                             .Discrete_FIR_Filter_coeff_0(coeffs_shadow[0]),  // sfix14_En13
                                             .Discrete_FIR_Filter_coeff_1(coeffs_shadow[1]),  // sfix14_En13
                                             .Discrete_FIR_Filter_coeff_2(coeffs_shadow[2]),  // sfix14_En13
                                             .Discrete_FIR_Filter_coeff_3(coeffs_shadow[3]),  // sfix14_En13
                                             .Discrete_FIR_Filter_coeff_4(coeffs_shadow[4]),  // sfix14_En13
                                             .Discrete_FIR_Filter_coeff_5(coeffs_shadow[5]),  // sfix14_En13
                                             .Discrete_FIR_Filter_coeff_6(coeffs_shadow[6]),  // sfix14_En13
                                             .Discrete_FIR_Filter_coeff_7(coeffs_shadow[7]),  // sfix14_En13
                                             .Discrete_FIR_Filter_coeff_8(coeffs_shadow[8]),  // sfix14_En13
                                             .Discrete_FIR_Filter_coeff_9(coeffs_shadow[9]),  // sfix14_En13
                                             .Discrete_FIR_Filter_coeff_10(coeffs_shadow[10]),  // sfix14_En13
                                             .Discrete_FIR_Filter_coeff_11(coeffs_shadow[11]),  // sfix14_En13
                                             .Discrete_FIR_Filter_coeff_12(coeffs_shadow[12]),  // sfix14_En13
                                             .Discrete_FIR_Filter_coeff_13(coeffs_shadow[13]),  // sfix14_En13
                                             .Discrete_FIR_Filter_coeff_14(coeffs_shadow[14]),  // sfix14_En13
                                             .Discrete_FIR_Filter_coeff_15(coeffs_shadow[15]),  // sfix14_En13
                                             .Discrete_FIR_Filter_coeff_16(coeffs_shadow[16]),  // sfix14_En13
                                             .Discrete_FIR_Filter_coeff_17(coeffs_shadow[17]),  // sfix14_En13
                                             .Discrete_FIR_Filter_coeff_18(coeffs_shadow[18]),  // sfix14_En13
                                             .Discrete_FIR_Filter_coeff_19(coeffs_shadow[19]),  // sfix14_En13
                                             .Discrete_FIR_Filter_coeff_20(coeffs_shadow[20]),  // sfix14_En13
                                             .Discrete_FIR_Filter_coeff_21(coeffs_shadow[21]),  // sfix14_En13
                                             .Discrete_FIR_Filter_coeff_22(coeffs_shadow[22]),  // sfix14_En13
                                             .Discrete_FIR_Filter_coeff_23(coeffs_shadow[23]),  // sfix14_En13
                                             .Discrete_FIR_Filter_coeff_24(coeffs_shadow[24]),  // sfix14_En13
                                             .Discrete_FIR_Filter_coeff_25(coeffs_shadow[25]),  // sfix14_En13
                                             .Discrete_FIR_Filter_coeff_26(coeffs_shadow[26]),  // sfix14_En13
                                             .Discrete_FIR_Filter_coeff_27(coeffs_shadow[27]),  // sfix14_En13
                                             .Discrete_FIR_Filter_coeff_28(coeffs_shadow[28]),  // sfix14_En13
                                             .Discrete_FIR_Filter_coeff_29(coeffs_shadow[29]),  // sfix14_En13
                                             .Discrete_FIR_Filter_coeff_30(coeffs_shadow[30]),  // sfix14_En13
                                             .Discrete_FIR_Filter_coeff_31(coeffs_shadow[31]),  // sfix14_En13
                                             .Discrete_FIR_Filter_coeff_32(coeffs_shadow[32]),  // sfix14_En13
                                             .Discrete_FIR_Filter_coeff_33(coeffs_shadow[33]),  // sfix14_En13
                                             .Discrete_FIR_Filter_coeff_34(coeffs_shadow[34]),  // sfix14_En13
                                             .Discrete_FIR_Filter_coeff_35(coeffs_shadow[35]),  // sfix14_En13
                                             .Discrete_FIR_Filter_coeff_36(coeffs_shadow[36]),  // sfix14_En13
                                             .Discrete_FIR_Filter_coeff_37(coeffs_shadow[37]),  // sfix14_En13
                                             .Discrete_FIR_Filter_coeff_38(coeffs_shadow[38]),  // sfix14_En13
                                             .Discrete_FIR_Filter_coeff_39(coeffs_shadow[39]),  // sfix14_En13
                                             .Discrete_FIR_Filter_coeff_40(coeffs_shadow[40]),  // sfix14_En13
                                             .Discrete_FIR_Filter_coeff_41(coeffs_shadow[41]),  // sfix14_En13
                                             .Discrete_FIR_Filter_coeff_42(coeffs_shadow[42]),  // sfix14_En13
                                             .Discrete_FIR_Filter_out(Filter_Out_1)  // sfix15_En13
                                             );
  assign filter_out = Filter_Out_1;

  assign ce_out = clk_enable;

endmodule  // Programmable_FIR_via_Registers

